### ISSUE TITLE
[BUG] RPC reports a deserialize issue when an unknown method is called

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/weld#133]
When I call an actor that doesn't implement a certain message, I get the error
```
~/github.com/wasmcloud/weld/rpc-rs ➜ wash call MARGEE37MWZL2CY3WLUBQ7MMLZA3XTGKPPPPLGBFTAXVQU2C7PPZOFOW Tesst.PartOne '{}' -t 10000

deserialization: response to Tesst.PartOne: deserialization: invalid type: unit value, expected byte array
```

However, subscribing to NATS on `*.>` I can actually see that the error is that the method was not implemented, and that error string is what's failing to deserialize as an `InvocationResponse`. This is an error message that's misleading and can cause confusion

**Comment by stevelr** [comment]
is the error that the host isn't returning InvocationResponse? That struct has a field for an error.

**Comment by stevelr** [comment]
We could catch the deserialization error and return a better error, but this should also be fixed in the host.

Another implementation - like a golang capability provider, or a future component, could hit the same error, without wasmbus-rpc being in the code path.
