### ISSUE TITLE
Go codegen: Optional strings

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/weld#134]
Optional string fields need to be checked for a non-empty value, and if empty, encode a `WriteNil` value instead of a string value.  When the host receives a string value (to include an empty string), specifically for the below error field, it treats it as an error.

This is the edited code from the `core` tinygo module
```go
// MEncode serializes a InvocationResponse using msgpack
func (o *InvocationResponse) MEncode(encoder msgpack.Writer) error {
	encoder.WriteMapSize(4)
	encoder.WriteString("msg")
	encoder.WriteByteArray(o.Msg)
	encoder.WriteString("invocation_id")
	encoder.WriteString(o.InvocationId)
	encoder.WriteString("error")
	if len(o.Error) > 0 {
		encoder.WriteString(o.Error)

	} else {
		encoder.WriteNil()
	}
	encoder.WriteString("content_length")
	encoder.WriteUint64(o.ContentLength)

	return encoder.CheckError()
}
```

**Comment by connorsmith256** [comment]
@jordan-rash is this still relevant with your ongoing work with Go codegen?

**Comment by jordan-rash** [comment]
I don’t think so. All these old PRs and Issues would need to be solved through anyway
