### ISSUE TITLE
determine repository location and structure for smithy interface files

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/weld#2]
The current set of smithy models were developed under `wasmcloud/weld/examples/interface/`, where they will live until the smithy interfaces are stabilized. After that, they should move somewhere else.

A more permanent home needs to be identified for 
- core model files (wasmcloud-model & wasmcloud-core)
- interfaces that define capability providers, and 
- example code

The destination for each of these types isn't necessarily the same.

Because the core model files are tightly connected to both codegen and rpc-rs, those model files will likely stay in this repo (unless this repo is also split up).

**Comment by stevelr** [comment]
Current plan:

- interface definitions - IDL will be in actor-interfaces repository
- shared libraries, generated with codegen from IDL will be in actor-interfaces repository

Some interfaces, and corresponding libraries, that are not "official" interfaces will be in the examples repository

**Comment by stevelr** [comment]
Updated plan:
- Interface files will be in the new repo wasmcloud/interfaces. This includes "core" and anything that will be migrating from actor-interfaces.
- shared libraries will be generated into the wasmcloud/interfaces repo.

- an "examples" subdirectory within wasmcloud/interfaces will contain other interfaces that are supported, but may have less documentation and testing.

**Comment by autodidaddict** [comment]
@stevelr marking items as done in the zenboard doesn't appear to close the issue.
